name: hyperion
version: '0.1.0.0'
author: David Simmons-Duffin
maintainer: davidsd@gmail.com
license: MIT

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -Wunused-packages

dependencies:
- base
- process
- time
- random
- filepath
- attoparsec
- bytestring
- mtl
- text
- distributed-static
- distributed-process
- distributed-process-async
- network-transport
- network-transport-tcp
- network
- network-bsd
- unix
- binary
- transformers
- stm
- ghc-prim
- directory
- aeson
- containers
- pretty-show
- pretty
- exceptions
- lens
- extra
- concurrent-output
- shell-escape
- rank1dynamic
- sqlite-simple
- resource-pool
- monad-control
- transformers-base
- optparse-applicative
- servant
- servant-server
- wai
- warp
- mime-mail
- binaryhash
- async
- constraints
- template-haskell
- binary-instances
- vector

library:
  source-dirs: src
