flags: {}
packages:
- '.'
- './example'
extra-deps:
- distributed-static-0.3.9
- sqlite-simple-0.4.18.0
- direct-sqlite-2.3.26
- git: https://github.com/davidsd/network-transport-tcp
  commit: feea8507d25390c57d531c4ab8894f58e716c721
- git: https://github.com/davidsd/distributed-process.git
  commit: 144818f5174522ee4a027a4681ec047e0567c11b
- git: https://github.com/davidsd/distributed-process-async.git
  commit: bfb2a156965fe62ed30c7eacfc09a410bb7c3705
resolver: lts-16.0
