flags: {}
packages:
- '.'
- './example'
extra-deps:
- distributed-static-0.3.9
- git: https://github.com/davidsd/network-transport-tcp
  commit: feea8507d25390c57d531c4ab8894f58e716c721
- git: https://github.com/davidsd/distributed-process.git
  commit: 144818f5174522ee4a027a4681ec047e0567c11b
- git: https://github.com/davidsd/distributed-process-async.git
  commit: bfb2a156965fe62ed30c7eacfc09a410bb7c3705
- git: https://gitlab.com/pkravchuk/binaryhash.git
  commit: f5760f1912b97bdb9fe5ed5ce635010065c0c612
- git: https://gitlab.com/davidsd/hyperion-static.git
  commit: 61f990db312805bc4a87e3dc9ae46fc568062c6b
resolver: lts-17.4
